### PR TITLE
fixes several things related to deps

### LINKED ISSUE #656: Hortonworks Distro doesn't comple
https://gist.github.com/agibsonccc/5c15d6b8637619a2c8f8ce99039c5900

This is likely solved by adding the horton works repo:
http://repo.hortonworks.com/content/repositories/releases/

### PR DESCRIPTION
**Pull request by andypetrella**
* spark 2.x.y (like 2.0.0-preview) can now be used
* mapr repo for mapr deps
* spark version with weird format after x.y.z

**WARN** 
* Still have to migrate the tachyon stuff to alluxio for 2+
* 2+ spark version doesn't compile yet, API changes need some massage (Dataset, REPL, ...)
* CDH 1.6.0 seems to have backported some 2 stuff hence needs some specific fu ( see #655 )

should fix #656 and #465 

cc @huitseeker @vidma 
@agibsonccc

### CODE REVIEW

File: project/Dependencies.scala [hunk 1]
```diff
@@ -150,7 +152,7 @@ object Dependencies {
   val commonsExec = "org.apache.commons" % "commons-exec" % "1.3" force()
   val commonsCodec = "commons-codec" % "commons-codec" % "1.10" force()
 
-  val defaultGuavaVersion = sys.props.getOrElse("guava.version", "14.0.1") // 16.0.1 for cassandra connector 1.6-M1
+  val defaultGuavaVersion = sys.props.getOrElse("guava.version", "16.0.1") // 16.0.1 for cassandra connector 1.6-M1
```
Comment (vidma) [inline project/Dependencies.scala]: shouldn't this be dependent on spark-version?

File: project/Shared.scala [hunk 2]
```diff
@@ -121,11 +121,16 @@ object Shared {
...
+        .map(_.toInt).take(3) match {
           case List(1, y, z) if y <= 3 => "0.5.0"
           case List(1, 4, z) => "0.6.4"
           case List(1, 6, z) => "0.8.2"
           case List(1, y, z) => "0.7.1"
+          case List(2, y, z) =>
+            // need to change to use Alluxio instead...
+            // http://search.maven.org/#search|ga|1|alluxio
+            // http://www.alluxio.com/2016/04/getting-started-with-alluxio-and-spark/
+            "0.7.1"
```
Comment (vidma) [inline project/Shared.scala]: just throw exception? or fix it

File: project/Dependencies.scala [hunk 3]
```diff
@@ -25,24 +25,26 @@ object Dependencies {
   val akkaSlf4j = akkaGroup %% "akka-slf4j" % akkaVersion
 
   val scala_2_1X = "2\\.1([0-9])\\.[0-9]+.*".r
-  val spark_1_X = "[a-zA-Z]*1\\.([0-9]+)\\.([0-9]+).*".r
+  val spark_X_Y = "[a-zA-Z]*([0-9]+)\\.([0-9]+)\\.([0-9]+).*".r
   val extractVs = "[a-zA-Z]*(\\d+)\\.(\\d+)\\.(\\d+).*".r
 
-  val defaultSparkVersion = sys.props.getOrElse("spark.version", "1.6.0")
+  val defaultSparkVersion = sys.props.getOrElse("spark.version", "1.6.1")
```
Comment (vidma) [inline project/Dependencies.scala]: P.S. word `default` looks misleading here. It's the **actual** `spark.version` to use
(not to be fixed in this PR ;] ).

File: project/Dependencies.scala (hunk 1 above)
Comment (andypetrella) [inline project/Dependencies.scala]: Spark is pretty decoupled from that now, the hard deps on 14 is on old versions (AFAIK).
So it can be anything, 16 is good for cassandra which is the main blocker that I've seen so far

sounds good?

File: project/Shared.scala (hunk 2 above)
Comment (andypetrella) [inline project/Shared.scala]: No it's not a real problem unless you want to use Alluxio, which is still rare.
We'll work on that, but it shouldn't prevent ppl to be able to try the 2.0.0

that's why I keep it there without throwing

File: project/Dependencies.scala (hunk 3 above)
Comment (andypetrella) [inline project/Dependencies.scala]: you're damn right!!!
We should change that for all these vars, good point

**Comment by andypetrella** [comment]
let's bring this one in, so we can move forward and fix the alluxio and naming in separate PRs
